### ISSUE TITLE
The plugin isn't setup correctly for download from asset library

### ISSUE THREAD

**Issue by Zylann** [SIsilicon/Volume-Renderer#1]
When I try to download the asset from the the editor using the assetlib tab, download succeeds but I am unable to open anything because the project is in a subfolder.
This is all I see after download:
![image](https://user-images.githubusercontent.com/1311555/40582206-e7dd6dd6-616e-11e8-9407-005b5d4dec6f.png)

**Comment by SIsilicon** [comment]
That doesn't seem right at all..
default_env.tres *and* icon.png should both be in the volume project sub folder.
See, the reason why I set up the folder system like that was so that the volume generator would not be imported by godot.
That was *before* I new of .gdignore.

Also wouldn't you still be able to open it? You know by opening the project.godot file?

You obviously have more experience than me so I just want to know.

**Comment by Zylann** [comment]
I can open the sub-project yeah, but not from Godot. The flow of creating a project and installing your addon in it doesn't work.

**Comment by SIsilicon** [comment]
Installing the addon.Oh that's in volume project/addons/"the addon".
I always thought the workflow was to just copy and paste that mentioned folder into your other project's addon folder. Then going into project settings to enable it.

**Comment by SIsilicon** [comment]
Well I guess I can say this. I am working on a mesh voxelizer that will be _inside_ Godot. Eliminating the need for an external volume generator. When it's ready I can get rid of the current folder hierarchy in the place of the more familiar one.

**Comment by SIsilicon** [comment]
Ok. Its now version 1.3, and the volume generator is now inside the editor itself.
Now I just need to update it from the asset store.
